---
image: "buluma/github-action-molecule:4.0.5"

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  PY_COLORS: 1

molecule:
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  retry: 1
  parallel:
    matrix:
      - image: "alpine"
        tag: "latest"
      - image: "amazonlinux"
        tag: "latest"
      # - image: "debian"     # TODO fatal: [reboot-debian-bullseyepy310-ansible-5]: FAILED! => {"changed": false, "msg": "No package matching 'needrestart' is available"}
      #  tag: "bullseye"
      # - image: "debian"
      #  tag: "bookworm"
      - image: "fedora"
        tag: "34"
      - image: "fedora"
        tag: "latest"
      - image: "fedora"
        tag: "rawhide"
      # - image: "opensuse"
      #  tag: "latest"
      - image: "docker-ubuntu2204-ansible"
        tag: "latest"
      # - image: "ubuntu"     # TODO fatal: [reboot-ubuntu-bionic]: FAILED! => {"changed": false, "msg": "No package matching 'needrestart' is available"}
      #  tag: "bionic"

molecule-testing:
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "testing"
  retry: 2
  parallel:
    matrix:
      - image: "docker-ubuntu2204-ansible"
        tag: "latest"

galaxy:
  script:
    - ansible-galaxy role info ${CI_PROJECT_NAMESPACE}.reboot
